//
// Created by batuberk on 21.02.2024.
//

#ifndef RETROSNAKE_CONFIG_H
#define RETROSNAKE_CONFIG_H

#define USE_FIXED_WINDOW_SIZE 1
#define USE_GRID_LINES 1

#define FIXED_WINDOW_WIDTH 950
#define FIXED_WINDOW_HEIGHT 550

const int CELL_SIZE = 50;

#endif //RETROSNAKE_CONFIG_H
